import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from supabase import Client, create_client

# ── Path fix — allows running from scripts/ or anywhere ───────────────────────
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

# ── Config ─────────────────────────────────────────────────────────────────────

SELLER_ID = "16bd8883-cd2f-45aa-ac85-686b66e06791"

DATA_DIR = Path(__file__).resolve().parent.parent / "data2"
LOGS_DIR = Path(__file__).resolve().parent.parent / "logs"
INPUT_JSON = f"{DATA_DIR}/new_album_data_updated_cdn.json"

# ── Supabase client ────────────────────────────────────────────────────────────

load_dotenv()
supabase: Client = create_client(
    os.getenv("SUPABASE_URL"),
    os.getenv("SUPABASE_SERVICE_ROLE_KEY"),
)

# ── Logging ───────────────────────────────────────────────────────────────────

Path(LOGS_DIR).mkdir(parents=True, exist_ok=True)

log_filename = datetime.now().strftime("supabase_upload_%Y-%m-%d_%H-%M-%S.log")
log_filepath = f"{LOGS_DIR}/{log_filename}"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(log_filepath),
    ],
)
log = logging.getLogger(__name__)


# ── Upload ─────────────────────────────────────────────────────────────────────


def upload_to_supabase():
    log.info("=" * 60)
    log.info("Supabase Upload New Data started")
    log.info(f"Log file: {log_filepath}")
    log.info("=" * 60)

    # ── Load JSON ──────────────────────────────────────────────────
    log.info(f"Reading {INPUT_JSON} ...")
    try:
        with open(INPUT_JSON, "r", encoding="utf-8") as f:
            all_products = json.load(f)
    except FileNotFoundError:
        log.error(f"JSON file not found: {INPUT_JSON}")
        raise SystemExit("JSON file not found")
    except json.JSONDecodeError as e:
        log.error(f"Invalid JSON format: {e}")
        raise SystemExit("Invalid JSON file")
    except Exception as e:
        log.error(f"Unexpected error reading JSON file: {e}")
        raise SystemExit("Error reading JSON file")

    # Handle both list and dict shaped JSON
    products = (
        all_products if isinstance(all_products, list) else list(all_products.values())
    )

    if not products:
        log.info("No new products to insert — exiting.")
        return

    log.info(f"Found {len(products)} new products to insert\n")

    # ── Counters ───────────────────────────────────────────────────
    woodtableguy_products_success = 0
    woodtableguy_products_failed = 0
    woodtableguy_product_data_success = 0
    woodtableguy_product_data_failed = 0

    # ── Loop and insert ────────────────────────────────────────────
    for product in products:
        slug = product.get("slug", "unknown")

        try:
            # ── Step 1: Insert into fashionbroda_products ──────────
            # Map JSON keys to exact DB column names:
            #   product_image_url  (JSON) → product_image_urls  (DB)
            #   size_chart_url     (JSON) → size_chart_image_urls (DB)
            woodtableguy_products_row = {
                "seller_id": SELLER_ID,
                "brands": product.get("brand"),
                "slug": slug,
                "is_active": True,
                "is_deleted": False,
                "yupoo_album_url": product.get("yupoo_album_url"),
                "product_cover_image": product.get("product_cover_image"),
                "product_image_urls": product.get("product_image_url") or [],
            }

            # Upsert on slug — DB unique constraint prevents duplicates on re-run
            woodtableguy_products_response = (
                supabase.table("woodtableguy_products")
                .upsert(woodtableguy_products_row, on_conflict="slug")
                .execute()
            )

            if not woodtableguy_products_response.data:
                log.error(f"  ✗ Failed to insert woodtableguy_products: {slug}")
                woodtableguy_products_failed += 1
                continue

            log.info(f"  ✓ Inserted woodtableguy_products: {slug}")
            woodtableguy_products_success += 1

            # Get the autogenerated product id from the insert response
            # to link the product_data row back to it
            product_id = woodtableguy_products_response.data[0].get("id")
            log.info(f"  ↳ product_id: {product_id}")

            # ── Step 2: Insert into product_data ──────────────────
            # Only extract core DB columns — weidian, weight, craft,
            # construction, note etc. are intentionally excluded
            raw_pd = product.get("product_data") or {}
            woodtableguy_product_data_row = {
                "product_id": product_id,
                "price": raw_pd.get("price"),
                "product_title": raw_pd.get("product_title"),
                "sizes": raw_pd.get("sizes"),
            }

            woodtableguy_product_data_response = (
                supabase.table("woodtableguy_product_data")
                .upsert(woodtableguy_product_data_row, on_conflict="product_id")
                .execute()
            )

            if not woodtableguy_product_data_response.data:
                log.error(f"  ✗ Failed to insert woodtableguy_product_data: {slug}")
                woodtableguy_product_data_failed += 1
                continue

            log.info(f"  ✓ Inserted woodtableguy_product_data: {slug}")
            woodtableguy_product_data_success += 1

        except Exception as e:
            log.error(f"  ✗ Exception for {slug}: {e}")
            woodtableguy_product_data_failed += 1
            continue

    # ── Summary ────────────────────────────────────────────────────
    log.info(f"\n{'=' * 60}")
    log.info("Upload complete")
    log.info(f"  ✓ woodtableguy_products inserted: {woodtableguy_products_success}")
    log.info(
        f"  ✓ woodtableguy_product_data inserted:          {woodtableguy_product_data_success}"
    )
    log.info(f"  ✗ woodtableguy_products failed:   {woodtableguy_products_failed}")
    log.info(
        f"  ✗ woodtableguy_product_data failed:            {woodtableguy_product_data_failed}"
    )
    log.info(f"Log saved to: {log_filepath}")
    log.info("=" * 60)


if __name__ == "__main__":
    upload_to_supabase()
